# Generated by Django 4.2.4 on 2023-08-14 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('nome_usuario', models.CharField(max_length=50)),
                ('sobrenome_usuario', models.CharField(max_length=50)),
                ('matricula_usuario', models.CharField(max_length=7, primary_key=True, serialize=False, unique=True)),
                ('vertical_usuario', models.CharField(max_length=25)),
                ('gerencia_usuario', models.CharField(choices=[('MARIA ANGELICA', 'Maria Angelica'), ('FLAVIA BRASIL', 'Flavia Brasil'), ('AGATHA TRINDADE', 'Agatha Trindade')], default='Escolha a sua Gerencia', max_length=100)),
                ('email_usuario', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=100)),
            ],
        ),
    ]
