# Generated by Django 4.2.4 on 2023-08-18 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuarios_data_fotografia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='data_fotografia',
            new_name='data_cadastro',
        ),
    ]
