# Generated by Django 4.2.4 on 2023-08-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_rename_senha_usuarios_senha_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorasExtras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula_usuario_hora_extra', models.CharField(max_length=7)),
                ('mes_hora_extra', models.CharField(choices=[('JANEIRO', 'Janeiro'), ('FEVEREIRO', 'Fevereiro'), ('MARÇO', 'Março'), ('ABRIL', 'Abril'), ('MAIO', 'Maio'), ('JUNHO', 'Junho'), ('JULHO', 'Julho'), ('AGOSTO', 'Agosto'), ('SETEMBRO', 'Setembro'), ('OUTUBRO', 'Outubro'), ('NOVEMBRO', 'Novembro'), ('DEZEMBRO', 'Dezembro')], max_length=20)),
                ('horas_horas_extras', models.IntegerField()),
                ('minutos_horas_extras', models.IntegerField()),
                ('motivo_horas_extras', models.CharField(choices=[('RDM', 'Rdm'), ('REPROCESSAMENTO', 'Reprocessamento'), ('PROJETO', 'Projeto'), ('OUTROS', 'outros')], max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
